### ISSUE TITLE
Update package versions

### ISSUE THREAD

**Issue by multiwebinc** [Infamoustrey/bible-gateway-api#4]
I am building a website for my church and wanted to give this package a try, however, it uses a vulnerable version of axios.

> npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

You might want to get that updated to the latest version.

**Comment by Infamoustrey** [comment]
Pull requests are welcome.
